version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: nginx.treeipe.com
    hostname: nginx.treeipe.com
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    ports:
      - "8080:80"